language: node_js

node_js:
  - "6"
  - "8"
  - "10"

before_script:
  - npm run build
  - npm run bootstrap

after_success:
  - npm run coveralls

cache:
  directories:
    - node_modules
    - packages/creditjs/node_modules

git:
  depth: 5
